### ISSUE TITLE
Installation of Drupal 8 fails due to removal of default.settings.php file

### ISSUE THREAD

**Issue by maijs** [wunderkraut/build.sh#12]
My `site.make` file:

```
core = 8.0
projects[drupal][version] = 8.0.0
```

When installing using `./build.sh new`, I get the following error:

```
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                         [ok]
exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'Default settings file: The default settings file does not exist.        [error]

The Drupal installer requires that the <em class="placeholder">./sites/default/default.settings.php</em> file not be modified in any way from the
original download.' in /Users/myuser/Sites/mysite/drupal/core/includes/install.core.inc:2173
Stack trace:
#0 /Users/myuser/Sites/mysite/drupal/core/includes/install.core.inc(1014): install_display_requirements(Array, Array)
#1 /Users/myuser/Sites/mysite/drupal/core/includes/install.core.inc(648): install_verify_requirements(Array)
#2 /Users/myuser/Sites/mysite/drupal/core/includes/install.core.inc(526): install_run_task(Array, Array)
#3 /Users/myuser/Sites/mysite/drupal/core/includes/install.core.inc(116): install_run_tasks(Array)
#4 /Users/myuser/.composer/vendor/drush/drush/includes/drush.inc(721): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#5 /Users/myuser/.composer/vendor/drush/drush/includes/drush.inc(706): drush_call_user_func_array('install_drupal', Array)
#6 /Users/myuser/.composer/vendor/drush/drush/commands/core/drupal/site_install.inc(78): drush_op('install_drupal',
Object(Composer\Autoload\ClassLoader), Array)
#7 /Users/myuser/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(289): drush_core_site_install_version('minimal', Array)
#8 [internal function]: drush_core_site_install('minimal', 'install_configu...')
#9 /Users/myuser/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_core_site...', Array)
#10 /Users/myuser/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#11 [internal function]: drush_command('minimal', 'install_configu...')
#12 /Users/myuser/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#13 /Users/myuser/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(65): drush_dispatch(Array)
#14 /Users/myuser/.composer/vendor/drush/drush/includes/preflight.inc(64): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /Users/myuser/.composer/vendor/drush/drush/drush.php(12): drush_main()
```

I believe this is due to the fact that `default.settings.php` is removed in `def make`.

**Comment by maijs** [comment]
False alarm. I was trying to install a Drupal 8 site from `develop` branch which is Drupal 7 specific. `build.sh` in `d8` branch doesn't remove `default.settings.php`.
